// Generated by jextract

package com.github.netherbedrockcracker;

/**
 * {@snippet lang=c :
 * typedef struct _lldiv_t {
 *     long long quot;
 *     long long rem;
 * } lldiv_t
 * }
 */
public class lldiv_t extends _lldiv_t {

    lldiv_t() {
        // Should not be called directly
    }
}
